### ISSUE TITLE
در هر ریکوست اجرا میشود ؟

### ISSUE THREAD

**Issue by behroozbc** [codehaks/Lemon-Lite#1]
https://github.com/codehaks/Lemon/blob/1aacd7072ea4472a9facdf56e3c34d72c1df700d/src/Portal.Application/Common/CommitCommandPostProcessor.cs#L24
با سلام 
من در حال دیدن اموزش DDD شما هستم برای یه سوالی پیش اومدش 
این در هر ریکوستی که به MediatR داده میشود اجرا میشود ؟
مثال کوری های که فقط برای گرفتن اطلاعات از دیتابیس هستند هم اجرا میشود

**Comment by codehaks** [comment]
بله اجرا میشه 
برای حل این مشکل چند کار میشه انجام داد
اول تزریق وابستگی برای هر کامند جداگانه انجام بشه و فقط برای اونهایی که عملیات ذخیر دارن این رفتار اضافه بشه

دوم با استفاده از یک اینترفیس کامندهایی که قرار چیزی کامیت کنن رو مشخص کنیم و درون پست پروسسور چک کنیم که از همین روش کد تغییر کرد در برنچ 18 کامیت شد
